resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
- name: copr
  type: docker-image
  source:
    repository: quay.io/ahoi/concourse-copr-resource

resources:
- name: git-clone-resource
  type: git
  source:
    branch: master
    uri: https://github.com/drahnr/oregano.git

- name: git-pull-request-resource
  type: pull-request
  source:
    repo: drahnr/oregano
    access_token: {{github-token}}


- name: copr-resource
  type: copr
  source:
    login: {{copr-login}}
    token: {{copr-token}}
    url: {{copr-url}}

- name: oregano-test-fedora
  type: docker-image
  source:
    repository: quay.io/ratpoison/oregano-test-fedora
    username: {{quay-username}}
    password: {{quay-password}}

- name: oregano-test-ubuntu
  type: docker-image
  source:
    repository: quay.io/ratpoison/oregano-test-ubuntu
    username: {{quay-username}}
    password: {{quay-password}}

jobs:
  - name: pr-compile
    build_logs_to_retain: 50
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
        trigger: true
      - get: git-pull-request-resource
        trigger: true
    - task: compile
      timeout: 5m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-pull-request-resource
        run:
          path: sh
          args:
          - -exc
          - |
            ./waf configure build --debug --prefix=/tmp install
            ./build/test/microtests
          dir: "git-pull-request-resource"
      on_success:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          status: success
      on_failure:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          status: failure

  - name: compile
    build_logs_to_retain: 10
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
        trigger: true
      - get: git-clone-resource
        trigger: true
    - task: compile
      timeout: 15m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-clone-resource
        run:
          path: sh
          args:
          - -exc
          - |
            ./waf configure build --debug --prefix=/tmp install
            ./build/test/microtests
          dir: git-clone-resource

  - name: build-pkg-rpm
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
        trigger: true
      - get: git-clone-resource
        trigger: true
        passed: [compile]

    - task: create-rpm
      timeout: 10m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-clone-resource
        outputs:
        - name: srpm
        run:
          path: .concourse/fedora/buildrpm.sh
          dir: git-clone-resource

    - put: copr
      resource: copr-resource
      params:
        rpmbuild_dir: "srpm/rpmbuild/SRPMS"
        chroots: ["fedora-rawhide-x86_64", "fedora-26-x86_64", "fedora-25-x86_64"]
        enable_net: false
        max_n_bytes: 250000000
        project_id: 825
        regex: ".*oregano-.*\\.src\\.rpm$"

  - name: build-pkg-deb
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: oregano-test-ubuntu
        trigger: true
      - get: git-clone-resource
        trigger: true
        passed: [compile]

    - task: create-deb
      timeout: 10m
      image: oregano-test-ubuntu
      config:
        platform: linux
        inputs:
        - name: git-clone-resource
        run:
          path: debuild
          args: ["-i", "-us", "-uc", "-b"]
          dir: git-clone-resource

  - name: pr-build-pkg-rpm
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: oregano-test-fedora
        trigger: true
      - get: git-pull-request-resource
        trigger: true
        passed: [pr-compile]

    - task: create-rpm
      timeout: 10m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-pull-request-resource
        run:
          path: .concourse/fedora/buildrpm.sh
          dir: git-pull-request-resource

  - name: pr-build-pkg-deb
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: oregano-test-ubuntu
        trigger: true
      - get: git-pull-request-resource
        trigger: true
        passed: [pr-compile]

    - task: create-deb
      timeout: 10m
      image: oregano-test-ubuntu
      config:
        platform: linux
        inputs:
        - name: git-pull-request-resource
        run:
          path: debuild
          args: ["-i", "-us", "-uc", "-b"]
          dir: git-pull-request-resource
